### ISSUE TITLE
ignore node_modules?

### ISSUE THREAD

**Issue by kustomzone** [rllola/zeronet-react#1]
Hi Lola. Thanks for your effort~!
Dang.. i should know the answer.. but node_modules is getting included / signed.
(creates a huge content.json and requires +40mb zite)
If i understand correctly, gulp creates bundle,  therefore we don't require inclusion of all modules, so we should exclude them, right? I've tried "node_modules/.*" ..but to no avail.
Could you include your content.json directives as a sample?
Also, the linked blog tutorial is for creating 'zeroreact.coffee' would normally be in JS folder for 'all.js' compiling, so we should make zeroreact.js instead, right? (or maybe app.js is interfacing zeroframe only)

cheers, bot@zeroid.

**Comment by rllola** [comment]
Hi kustomzone,

So for my content.json ignore line I have this : `"ignore": "(data/.*|.git|node_modules|app|gulpfile.js|package.json|README.md|webpack.config.js)",
`
I will add a `content.json.example` to the project to give an example to help more people with it.

I am not sure to understand your second question... zeroframe.js is the javascript version of zeroframe.coffee I use it to interface with zeronet and get access to the db but I want to rewrite as an redux store library. Not sure if possible but I think that would be more clear for people on how to use it. At least I hope.

**Comment by kustomzone** [comment]
yup, that worked, thanks.
